/** Kinds of in-app notifications MF-1 raises (the `notifications.type` column). */
export const NOTIFICATION_TYPE = {
  PROJECT_ASSIGNED: 'PROJECT_ASSIGNED',
  PROJECT_CANCELLED: 'PROJECT_CANCELLED',
  CHANGE_REQUESTED: 'PROJECT_CHANGE_REQUESTED',
  CHANGE_RESOLVED: 'PROJECT_CHANGE_RESOLVED',
  BRIEF_EMAIL_FAILED: 'BRIEF_EMAIL_FAILED',
  MEDIA_READY: 'MEDIA_READY',
  MEDIA_FAILED: 'MEDIA_FAILED',
  CONTENT_CHANGES_REQUESTED: 'CONTENT_CHANGES_REQUESTED',
  EPISODE_OVERDUE: 'EPISODE_OVERDUE',
  HLS_LINK_DEAD: 'HLS_LINK_DEAD',
  PRICE_OUT_OF_RANGE: 'PRICE_OUT_OF_RANGE',
  PRICE_CHANGE_REQUEST: 'PRICE_CHANGE_REQUEST',
  EPISODE_PUBLISHED: 'EPISODE_PUBLISHED',
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];
