export const ACCESS_SOURCE = {
  NONE: 'NONE',
  FREE_STARTER: 'FREE_STARTER',
  FREE: 'FREE',
  PLAN: 'PLAN',
  EPISODE_PURCHASE: 'EPISODE_PURCHASE',
  SERIES_PURCHASE: 'SERIES_PURCHASE',
  ADMIN_GRANT: 'ADMIN_GRANT',
} as const;

export type AccessSourceName = (typeof ACCESS_SOURCE)[keyof typeof ACCESS_SOURCE];

export const ACTOR_TYPE = {
  GUEST: 'GUEST',
  MEMBER: 'MEMBER',
} as const;

export type ActorType = (typeof ACTOR_TYPE)[keyof typeof ACTOR_TYPE];

export const ACCESS_METHOD = {
  REGISTER_OR_LOGIN: 'REGISTER_OR_LOGIN',
  MONTHLY_PLAN: 'MONTHLY_PLAN',
  UNLOCK_EPISODE: 'UNLOCK_EPISODE',
  UNLOCK_SERIES: 'UNLOCK_SERIES',
  OBTAIN_COIN: 'OBTAIN_COIN',
} as const;

export type AccessMethod = (typeof ACCESS_METHOD)[keyof typeof ACCESS_METHOD];

export const NEXT_ACTION = {
  REGISTER_OR_LOGIN: 'REGISTER_OR_LOGIN',
  OBTAIN_COIN: 'OBTAIN_COIN',
  UNLOCK_EPISODE: 'UNLOCK_EPISODE',
  UNLOCK_SERIES: 'UNLOCK_SERIES',
  MONTHLY_PLAN: 'MONTHLY_PLAN',
  HANDOFF_TO_PLAYBACK: 'HANDOFF_TO_PLAYBACK',
} as const;

export type NextAction = (typeof NEXT_ACTION)[keyof typeof NEXT_ACTION];
