/** Content events of PROJECT_OVERVIEW.md §4.1.6 (the `audit_logs.action` column). */
export const CONTENT_EVENT = {
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  IDEA_FILE_UPLOADED: 'IDEA_FILE_UPLOADED',
  FEE_ALLOCATED: 'FEE_ALLOCATED',
  FEE_TOPPED_UP: 'FEE_TOPPED_UP',
  FEE_CORRECTED: 'FEE_CORRECTED',
  PROJECT_ASSIGNED: 'PROJECT_ASSIGNED',
  STUDIO_HANDOFF_SENT: 'STUDIO_HANDOFF_SENT',
  STUDIO_CHANGED: 'STUDIO_CHANGED',
  STUDIO_LINK_RESENT: 'STUDIO_LINK_RESENT',
  STUDIO_ACCEPTED: 'STUDIO_ACCEPTED',
  STUDIO_DECLINED: 'STUDIO_DECLINED',
  PROJECT_CANCELLED: 'PROJECT_CANCELLED',
  PROJECT_COMPLETED: 'PROJECT_COMPLETED',
  PROJECT_UNDER_REVISION: 'PROJECT_UNDER_REVISION',
  MEDIA_SUBMITTED: 'MEDIA_SUBMITTED',
  MEDIA_READY: 'MEDIA_READY',
  MEDIA_FAILED: 'MEDIA_FAILED',
  CONTENT_CHANGES_REQUESTED: 'CONTENT_CHANGES_REQUESTED',
  CONTENT_APPROVED: 'CONTENT_APPROVED',
  AI_LABEL_APPLIED: 'AI_LABEL_APPLIED',
  COMPLIANCE_PASSED: 'COMPLIANCE_PASSED',
  COMPLIANCE_FAILED: 'COMPLIANCE_FAILED',
  EPISODE_PRICED: 'EPISODE_PRICED',
  PRICE_OUT_OF_RANGE: 'PRICE_OUT_OF_RANGE',
  PROJECT_CHANGE_REQUESTED: 'PROJECT_CHANGE_REQUESTED',
  PROJECT_CHANGE_ACCEPTED: 'PROJECT_CHANGE_ACCEPTED',
  PROJECT_CHANGE_REJECTED: 'PROJECT_CHANGE_REJECTED',
  EPISODE_SCHEDULED: 'EPISODE_SCHEDULED',
  EPISODE_PUBLISHED: 'EPISODE_PUBLISHED',
  EPISODE_UNPUBLISHED: 'EPISODE_UNPUBLISHED',
} as const;

export type ContentEvent = (typeof CONTENT_EVENT)[keyof typeof CONTENT_EVENT];

/** The entities an event can be about. */
export type AuditEntity =
  | 'Movie'
  | 'Episode'
  | 'MovieIdeaFile'
  | 'TokenLedgerEntry'
  | 'StudioHandoff'
  | 'MediaAsset'
  | 'ContentReview'
  | 'AiContentLabel'
  | 'Publication'
  | 'PriceAlert'
  | 'ProjectChangeRequest';
