/** Kinds of in-app notifications the platform raises (the `notifications.type` column). */
export const NOTIFICATION_TYPE = {
  // MF-1 — movie projects
  PROJECT_ASSIGNED: 'PROJECT_ASSIGNED',
  PROJECT_CANCELLED: 'PROJECT_CANCELLED',
  CHANGE_REQUESTED: 'PROJECT_CHANGE_REQUESTED',
  CHANGE_RESOLVED: 'PROJECT_CHANGE_RESOLVED',
  BRIEF_EMAIL_FAILED: 'BRIEF_EMAIL_FAILED',
  STUDIO_ACCEPTED: 'STUDIO_ACCEPTED',
  STUDIO_DECLINED: 'STUDIO_DECLINED',
  TOKEN_GRANTED: 'TOKEN_GRANTED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  TOKEN_ALLOCATED: 'TOKEN_ALLOCATED',
  MEDIA_READY: 'MEDIA_READY',
  MEDIA_FAILED: 'MEDIA_FAILED',
  CONTENT_APPROVED: 'CONTENT_APPROVED',
  CONTENT_CHANGES_REQUESTED: 'CONTENT_CHANGES_REQUESTED',
  EPISODE_OVERDUE: 'EPISODE_OVERDUE',
  HLS_LINK_DEAD: 'HLS_LINK_DEAD',
  PRICE_OUT_OF_RANGE: 'PRICE_OUT_OF_RANGE',
  PRICE_CHANGE_REQUEST: 'PRICE_CHANGE_REQUEST',
  EPISODE_PUBLISHED: 'EPISODE_PUBLISHED',
  // MF-2 — Coin, daily reward and monthly plan
  COIN_TOPUP_SUCCESS: 'COIN_TOPUP_SUCCESS',
  COIN_BONUS_EXPIRING: 'COIN_BONUS_EXPIRING',
  COIN_LOW_BALANCE: 'COIN_LOW_BALANCE',
  SUB_RENEWED: 'SUB_RENEWED',
  SUB_RENEWAL_FAILED: 'SUB_RENEWAL_FAILED',
  SUB_EXPIRING: 'SUB_EXPIRING',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  EPISODE_ACCESS_REFUNDED: 'EPISODE_ACCESS_REFUNDED',
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];