/** Reasons of this module travel in `error.details.reason`. */
export const TOPUP_REASON = {
  AMOUNT_OUT_OF_RANGE: 'TOPUP_AMOUNT_OUT_OF_RANGE',
  ALREADY_SETTLED: 'TOPUP_ALREADY_SETTLED',
  NOT_PAYABLE: 'TOPUP_NOT_PAYABLE',
  AMOUNT_MISMATCH: 'TOPUP_AMOUNT_MISMATCH',
  NOT_FOUND: 'TOPUP_NOT_FOUND',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  INVALID_CALLBACK: 'CALLBACK_INVALID',
  MISSING_SIGNATURE: 'CALLBACK_MISSING_SIGNATURE',
} as const;
